# Generated by Django 4.2.7 on 2025-09-15 05:38

from django.db import migrations
import django_bleach.models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_post_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="content",
            field=django_bleach.models.BleachField(),
        ),
    ]
