# Generated by Django 5.2.6 on 2025-09-17 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_post_content"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"permissions": [("can_delete_post", "Can delete post")]},
        ),
    ]
