# Generated by Django 5.2.6 on 2025-09-20 07:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_post_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name="post",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_featured", True)),
                fields=("is_featured",),
                name="unique_featured_post",
            ),
        ),
    ]
