# Generated by Django 5.2.6 on 2025-10-08 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_apikey"),
    ]

    operations = [
        migrations.AddField(
            model_name="apikey",
            name="is_read_only",
            field=models.BooleanField(default=True),
        ),
    ]
