"""
Django settings for DjangoRev project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from decouple import config

import dj_database_url



def str_to_bool(v):
    return str(v).lower() in ("true", "1", "t", "yes")

DEBUG = str_to_bool(config("DEBUG", default=False))


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')


ALLOWED_HOSTS = [config('RENDER_EXTERNAL_HOSTNAME', default='localhost'),'127.0.0.1']

#Bleach Settings
BLEACH_ALLOWED_TAGS = [
    'p', 'b', 'i', 'a', 'strong', 'em', 'ul', 'ol', 'li', 'br', 'span', 'div',
    'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'blockquote', 'code', 'pre'
]
BLEACH_ALLOWED_ATTRIBUTES = {
    'a': ['href', 'title', 'target'],
    'p': ['class', 'style'],
    'span': ['class', 'style'],
    'div': ['class', 'style'],
}
BLEACH_ALLOWED_STYLES = ['color', 'font-weight', 'font-size']
BLEACH_STRIP_COMMENTS = True
BLEACH_STRIP_TAGS = True
BLEACH_DEFAULT_WIDGET = 'tinymce.widgets.TinyMCE'


TINYMCE_DEFAULT_CONFIG = {
    "height": 500,
    "menubar": "edit insert view format tools table help",
    "plugins": "link image code lists preview",
    "toolbar": "undo redo | bold italic underline | bullist numlist | link image | code",
    "content_style": "body { font-family:inherit; font-size:inherit; }",  # inherits your template CSS
}


INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "core",
    "userprofiles",
    "easy_thumbnails",
    "tinymce",
    "django_bleach",
    "debug_toolbar",
    "rest_framework",
    "django_filters",
    "drf_spectacular",
    "rest_framework.authtoken"

]

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "core.api.authentication.APIKeyAuthentication",  
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",  
    ),

    "DEFAULT_THROTTLE_CLASSES": [
        "core.api.throttling.APIKeyRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
        "rest_framework.throttling.AnonRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "api_key": "100/day",
        "user": "500/day",
        "anon": "50/day"
    },

    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticatedOrReadOnly",
    ),
    "DEFAULT_FILTER_BACKENDS": (
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ),
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 10,
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",


}


SPECTACULAR_SETTINGS = {
    'TITLE': 'Meridian Blog API',
    'DESCRIPTION': 'API for Meridian blog posts and categories',
    'VERSION': '1.0.0',
}


MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "Meridian.middleware.RequestTimingMiddleware",
    'debug_toolbar.middleware.DebugToolbarMiddleware',
]

# settings.py
INTERNAL_IPS = [
    '127.0.0.1',
]

ROOT_URLCONF = "Meridian.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "core.context_processors.site_info"
            ],
        },
    },
]

WSGI_APPLICATION = "Meridian.wsgi.application"

# settings for easy-thumbnails
THUMBNAIL_ALIASES = {
    "": {
        "post_list": {"size": (400, 250), "crop": True},
    },
}

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

if DEBUG:
    # Local dev with sqlite
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }
    DEFAULT_FILE_STORAGE = "django.core.files.storage.FileSystemStorage"
    MEDIA_URL = "/media/"
    MEDIA_ROOT = BASE_DIR / "media"

else:
    # Production with Postgres
    DATABASES = {
        "default": dj_database_url.config(conn_max_age=600,ssl_require=True)
    }
    DEFAULT_FILE_STORAGE = "storages.backends.s3boto3.S3Boto3Storage"
    THUMBNAIL_DEFAULT_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
    MEDIA_URL = f"https://{config('SUPABASE_PROJECT_REF')}.supabase.co/storage/v1/object/public/{config('AWS_STORAGE_BUCKET_NAME')}/"




#SUPABASE CONFIG

# Supabase Storage (S3-compatible) settings
AWS_ACCESS_KEY_ID = config("AWS_ACCESS_KEY_ID")  # Your Supabase S3 Access Key
AWS_SECRET_ACCESS_KEY = config("AWS_SECRET_ACCESS_KEY")  # Your Supabase S3 Secret Key
AWS_STORAGE_BUCKET_NAME = config("AWS_STORAGE_BUCKET_NAME", default="blog-images")  # Bucket name
AWS_S3_ENDPOINT_URL = config("AWS_S3_ENDPOINT_URL")  # e.g., https://your-project-id.supabase.co/storage/v1/s3
AWS_S3_REGION_NAME = config("AWS_S3_REGION_NAME", default="us-east-1")  # Adjust if needed
AWS_S3_SIGNATURE_VERSION = "s3v4"  # Required for custom endpoints
AWS_QUERYSTRING_AUTH = False
SUPABASE_PROJECT_REF = config('SUPABASE_PROJECT_REF')



# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "/static/" #At the app level
STATICFILES_DIRS = [BASE_DIR / 'static'] #At the root level
STATIC_ROOT = BASE_DIR / "staticfiles"


STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"




# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

LOGIN_REDIRECT_URL = '/'
